// Autogenerated from Pigeon (v0.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.example.pigeon_flutter_android;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class DeviceInfoPigeon {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DeviceInfoRequest {
    private String queryInfoDetails;
    public String getQueryInfoDetails() { return queryInfoDetails; }
    public void setQueryInfoDetails(String setterArg) { this.queryInfoDetails = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("queryInfoDetails", queryInfoDetails);
      return toMapResult;
    }
    static DeviceInfoRequest fromMap(Map<String, Object> map) {
      DeviceInfoRequest fromMapResult = new DeviceInfoRequest();
      Object queryInfoDetails = map.get("queryInfoDetails");
      fromMapResult.queryInfoDetails = (String)queryInfoDetails;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DeviceInfoReply {
    private String infoDetailsResult;
    public String getInfoDetailsResult() { return infoDetailsResult; }
    public void setInfoDetailsResult(String setterArg) { this.infoDetailsResult = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("infoDetailsResult", infoDetailsResult);
      return toMapResult;
    }
    static DeviceInfoReply fromMap(Map<String, Object> map) {
      DeviceInfoReply fromMapResult = new DeviceInfoReply();
      Object infoDetailsResult = map.get("infoDetailsResult");
      fromMapResult.infoDetailsResult = (String)infoDetailsResult;
      return fromMapResult;
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface DeviceInfoApi {
    DeviceInfoReply search(DeviceInfoRequest arg);

    /** Sets up an instance of `DeviceInfoApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, DeviceInfoApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DeviceInfoApi.search", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              DeviceInfoRequest input = DeviceInfoRequest.fromMap((Map<String, Object>)message);
              DeviceInfoReply output = api.search(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
